### PR TITLE
Alternate Solution for Issue #6 - Add PNG icons for Webkit

### PR DESCRIPTION
**Pull request by rudyjahchan**
Another solution for Issue #6 - This switches to PNG based icons when in a Webkit or Safari browser, circumventing the cause of the crash. I tried to follow the established coding pattern as much as possible. This is by no means ideal but may be acceptable until Chrome/Chromium/Safari have better support for SVG filtering.

### CODE REVIEW

**Comment by borismus** [comment]
Rudy I'd prefer hot-swapping for a different disabled base64 SVG as a workaround. Your patch makes the JS significantly bigger, and we should be using SVG anyway since we're dealing with differently sized devices with different DPIs.

**Comment by rudyjahchan** [comment]
@borismus Yeah, I was never enamored of this solution or the other one.

So you are suggesting instead of contrasting via a filter we just do a straight image swap? Or am I (as usual) am missing something?

**Comment by rudyjahchan** [comment]
(Also closing as clearly not going to be accepted).

**Comment by borismus** [comment]
Yep exactly. Svg swap.

**Comment by rudyjahchan** [comment]
Cool. I'll take a hack at it over the weekend if you don't get to it first. That or learn how to fix the chromium build ;-) Cheers

**Comment by borismus** [comment]
Thanks Rudy. Much appreciated!

**Pull request closed without merging**
