### PR TITLE
Position icons absolute to align them on parent element, if necessary.

### LINKED ISSUE #147: Button Position: Why `position: fixed;`
Hey,

I just have a short question: Why are the buttons placed with `position: fixed;`? Wouldn't it be slightly better to use `position: absolute;`, so the buttons will be aligned relative to the parent element's dimensions? What are the downsides, am I overlooking something?

Cheers,
Michaela

bildschirmfoto_2016-06-21_um_15_35_31

### PR DESCRIPTION
**Pull request by Fischaela**
This should fix #147

### CODE REVIEW

**Comment by borismus** [comment]
Could you test on desktop/android/ios?

**Comment by Fischaela** [comment]
Sure. 

I tested it on Android with a Chrome, iOS with Safari and Mac OS X with Safari and Chrome. Imo it looks good in all these browsers with the new `position: absolute;`.

However I could not test in browsers on Windows and Linux machines. Also I could not test the new CSS in Firefox, because I have a console reference error, claiming that `VRDisplays is not a function`. I think I am doing something else wrong here and that this has nothing to do with the modified CSS of the icons.

**Comment by pindiespace** [comment]
Firefox is trying to use the old VRDevices instead of VRDisplays.

**Comment by borismus** [comment]
Thanks!

**Comment by Fischaela** [comment]
@pindiespace Do you know, how I can fix this? This is a known issue, I guess?

**Comment by pindiespace** [comment]
It sounds like a conflict between the native WebVR currently in FF vs the polyfill.  The Nightly versions of FF have a version of WebVR native - but it is the old VRDevices, which was upgraded to VRDisplays in WebVR 1.0.  I'm not sure about FF mobile since I haven't tried setting up a debug environment for it.

The way to test is to use the web console to check if there is a navigator.getVRDevices present, On mobile, this can be hard to get to. So, in JavaScript, you could just do a temporary alert() in your JS code and test for navigator.getVRDevices and navigator.getVRDisplays.  

If neither navigator.getVRDevices or navigator.getVRDisplays aren't present, there is no WebVR, and the polyfill didn't load. If you have navigator.getVRDisplays, then anything trying navigator.getVRDevices would fail.

**Comment by borismus** [comment]
This is a temporary problem anyway, will go away once FF lands a WebVR 1.0
impl.

**Pull request merged**
