### PR TITLE
Disable depth buffer on render target

### PR DESCRIPTION
**Pull request by njam**
Increase in FPS from 18 to 23 for me with three.js master.

### CODE REVIEW

**Comment by borismus** [comment]
What does this actually do? Are depth tests still performed? @dmitriykovalev @mrdoob

**Comment by mrdoob** [comment]
Yeah. I don't think these are needed in this case.

**Comment by mrdoob** [comment]
I guess I was wrong 😇

**Comment by njam** [comment]
Hm, yes I think so too :|
Will do a PR, sorry!

**Pull request merged**
