### PR TITLE
Add option to prevent distortion

### PR DESCRIPTION
**Pull request by jensarps**
Having the CardboardDistorter active leads to imported models being drawn incorrectly in one of my experiments, so I need to be able to turn it off (at least until I find the cause of this, which, hm, well, might take pretty long).

I figured it might be a good idea to add an option for disabling the distorter, as others might run into similar issues as well.

### CODE REVIEW

**Comment by borismus** [comment]
Could you also amend the README.md with that information?

**Comment by jensarps** [comment]
Thanks for the merge!

> Could you also amend the README.md with that information?

Sure, do you want me to create a new PR for this (as this one is already merged), or should I add the changes here?

**Comment by borismus** [comment]
A new PR would be amazing. Thanks!

**Comment by jensarps** [comment]
Added to README in #58.

**Pull request merged**
