### PR TITLE
add `node_modules` to `.gitignore`

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by borismus** [comment]
Why? Kinda nice to be able to just run the thing from checkout, isn't it?

**Comment by cvan** [comment]
> Why? Kinda nice to be able to just run the thing from checkout, isn't it?

if it's up to date, yeah. it's a lot of noise, and it can be difficult when going to revisions in the past, if the modules weren't updated correctly. if you want to keep them checked in, that's fine. most npm projects I've seen stop doing that. whatever's easiest for users/devs I suppose.

**Comment by borismus** [comment]
I prefer to keep as is for now.

**Comment by cvan** [comment]
okay, that's fine

**Pull request closed without merging**
