### PR TITLE
Fix desktop VR compatibility

### PR DESCRIPTION
**Pull request by brianpeiris**

### CODE REVIEW

**Comment by borismus** [comment]
Thanks, Could you explain what this is fixing?

**Comment by pindiespace** [comment]
Well, my own take on this is there should be an option to do stereo view on desktop, instead of automatically locking you to fullscreen on desktop. Not only is it helpful to develop apps, but there are many situations (e.g. presentation to a group of people) where showing the stereo view from the laptop would be very helpful. Not everyone in the audience is going to have a headset or smartphone, and just showing a 3D scene doesn't help understanding when marketing the WebVR concept.

**Comment by brianpeiris** [comment]
Without this fix you can't enter VR mode in the latest Chromium WebVR build. The VR button doesn't show at all.

**Comment by borismus** [comment]
Thanks for the PR. The real solution is here, will be merged into master soon (as soon as I've tested stage parameters on Vive): https://github.com/borismus/webvr-boilerplate/commit/a54f0459a6aec7858d06817db38ec9cbcb804b27

**Comment by brianpeiris** [comment]
Gotcha, thanks. I'll close this one.

**Pull request closed without merging**
