### PR TITLE
Borismus/master

### PR DESCRIPTION
**Pull request by pindiespace**
Add Unique ID to Util.js. Other edits are just re-syncing my fork with the master.

### CODE REVIEW

**Comment by brianpeiris** [comment]
What purpose would this unique id serve?

(P.S. Typically a pull request should be as clean as possible, consisting of only the commits and file changes necessary to accomplish its goal. There's a lot of noise in this commit list and all of the file modes have changed unnecessarily)

**Comment by pindiespace** [comment]
Yes, it was messy because I transferred the project, rather than starting with a new one.

As far as a Unique ID - currently the boilerplate is incompatible with web page layouts. The code only works when you "fullwindow" the page, and you can't embed the code inside any kind of player. This is contrary to both responsive and adaptive design strategy. 

The specific problems are:
1. boilerplate can't handle using a parent element which is not document.body.
2. You can't put multiple managers on one page - they would all receive any button events

The result is that there is no way to provide graceful Ux for people in different use contexts. In particular, if you had a gallery of VR scenes you couldn't use the boilerplate - you have to put in a static image linked to a fullpage boilerplate. On many people's devices, this will fail. However, if the scene could run embedded in a standard page, you can provide text context plus some view of the scene for the fraction of users who will have WebGL but not be able to use VR.

The biggest Ux problem with the current mode is that you jump to a scene which may not run on many user's systems. The dialog helper for screen orientation is great, but you don't have the ability to "try before you by" - in other words, a version of the animated scene running in a larger DOM. So, you can't build animated galleries.

A Unique ID is a start to making the boilerplate "player-friendly" by solving Problem #2, so the manager could build a custom event. There might be other ways of solving this, but it changes the framework the least. 

This way, if you have multiple managers, they could filter out their own events, and wouldn't collide. 

I separated out Problem #1 (which is why there is noise underneath the actual change). This would require more mods to the boilerplate, so that it could use any parent element, not just document.body. It is harder, since if you add the boilerplate to an element in the DOM, differing fullscreen implementations in different browsers have to be handled, in addition to managing styles on the drawing canvas applied by external stylesheets. I worked out a solution, but required so many changes I filtered it out.

If both Problem #1 and Problem #2 were solved, the boilerplate could be used to build galleries, and could also be the basis for more complex VR players. Otherwise, the boilerplate isn't really implementing responsive design by default.

**Comment by bumblehead** [comment]
+1 for using a unique id. This would benefit many web applications.

**Comment by brianpeiris** [comment]
@pindiespace Thanks for the detailed explanation. This certainly seems like a good idea. (I'd still try to clean up the pull request though, or create a new, clean PR if that's easier. Best to lower the barrier as much as possible, in order to have your code accepted.)

**Comment by pindiespace** [comment]
OK, will reset from blank clone -pete

**Pull request closed without merging**
